#!/bin/csh
set echo
set name = "ms"
#set name = "Scaling"
#set name = "Progress"
if ( $#argv ) set name = $1
set this_latex = pdflatex
echo $name
#set this_latex = latex
if( -e /usr/bin/acroread ) then
 set run = "acroread"
else
 set run = "open"
endif    
rm -f *.log *.out *.aux *.dvi *~ *.bbl *.blg
rm -f *.ps $name.pdf *.bak *.toc *.lof *.lot

if( $1 == "c" ) then
    exit
endif

if( $1 == "o" ) then
    $this_latex $name
else
    
    ls -l
    
    $this_latex $name
    if( $status != 0 ) then
	echo "done borked sompin. Exiting."
	exit
    endif
    bibtex $name
    $this_latex $name
    $this_latex $name
    $this_latex $name
    if( $1 != "n" ) then
	if( -e $name.dvi ) then
	echo "convert to pdf"
	    dvips -Ppdf -t letter -o $name.ps $name.dvi
	    ps2pdf $name.ps $name.pdf

	    if( $status != 0 )then
		print "dvipdf borked.  That's *really* too bad."
		exit
	    endif
	endif
	if( $1 == "n" && ( -e $name.pdf ) ) $run $name.pdf &
    endif	    
endif
# the end
